### ISSUE TITLE
Better css on example page

### ISSUE THREAD

**Issue by lazarofl** [lazarofl/angular-calendarium#2]
The layout at README is totally different from example page.

on example page:
![image](https://cloud.githubusercontent.com/assets/913314/12792031/043da4f4-ca91-11e5-9f37-99a02a27dca9.png)

on readme:
![image](https://cloud.githubusercontent.com/assets/913314/12792054/2271da58-ca91-11e5-8d76-fdbe33b1cc8f.png)

**Comment by DevCarlosAugusto** [comment]
Vou dar uma olhada no fim de semana. :+1:
